### ISSUE TITLE
Hello? How did you get the poses and scale_factor?

### ISSUE THREAD

**Issue by 459737087** [vitalemonate/depth2Cloud#2]

**Comment by vitalemonate** [comment]
Sorry for late reply. 
(1)For poses, you can use groundtruth poses.
(2)The scale factor, as mentioned in README.md, typically is 1000. For specific dataset, such as TUM, you can get scale factor from official instruction in the following website, https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats.
Best wishes!

**Comment by 459737087** [comment]
Thank u! and I'll try it
